# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QScrollBar, QSizePolicy, QSpinBox, QStatusBar,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(692, 808)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(190, 15, 96, 16))
        font = QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        self.label.setFont(font)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(170, 35, 26, 26))
        font1 = QFont()
        font1.setBold(True)
        self.pushButton.setFont(font1)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(270, 35, 26, 26))
        self.pushButton_2.setFont(font1)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(170, 65, 26, 26))
        self.pushButton_3.setFont(font1)
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(270, 65, 26, 26))
        self.pushButton_4.setFont(font1)
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(170, 95, 26, 26))
        self.pushButton_5.setFont(font1)
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(270, 95, 26, 26))
        self.pushButton_6.setFont(font1)
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(170, 125, 26, 26))
        self.pushButton_7.setFont(font1)
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(270, 125, 26, 26))
        self.pushButton_8.setFont(font1)
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(170, 155, 26, 26))
        self.pushButton_9.setFont(font1)
        self.pushButton_10 = QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(270, 155, 26, 26))
        self.pushButton_10.setFont(font1)
        self.pushButton_11 = QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(170, 185, 26, 26))
        self.pushButton_11.setFont(font1)
        self.pushButton_12 = QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(270, 185, 26, 26))
        self.pushButton_12.setFont(font1)
        self.pushButton_13 = QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(420, 125, 26, 26))
        self.pushButton_13.setFont(font1)
        self.pushButton_14 = QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(320, 35, 26, 26))
        self.pushButton_14.setFont(font1)
        self.pushButton_15 = QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(320, 125, 26, 26))
        self.pushButton_15.setFont(font1)
        self.pushButton_16 = QPushButton(self.centralwidget)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(320, 185, 26, 26))
        self.pushButton_16.setFont(font1)
        self.pushButton_17 = QPushButton(self.centralwidget)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(420, 95, 26, 26))
        self.pushButton_17.setFont(font1)
        self.pushButton_18 = QPushButton(self.centralwidget)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(320, 95, 26, 26))
        self.pushButton_18.setFont(font1)
        self.pushButton_19 = QPushButton(self.centralwidget)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(420, 35, 26, 26))
        self.pushButton_19.setFont(font1)
        self.pushButton_20 = QPushButton(self.centralwidget)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(420, 185, 26, 26))
        self.pushButton_20.setFont(font1)
        self.pushButton_21 = QPushButton(self.centralwidget)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(320, 155, 26, 26))
        self.pushButton_21.setFont(font1)
        self.pushButton_22 = QPushButton(self.centralwidget)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(320, 65, 26, 26))
        self.pushButton_22.setFont(font1)
        self.pushButton_23 = QPushButton(self.centralwidget)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(420, 155, 26, 26))
        self.pushButton_23.setFont(font1)
        self.pushButton_24 = QPushButton(self.centralwidget)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(420, 65, 26, 26))
        self.pushButton_24.setFont(font1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(340, 15, 111, 16))
        self.label_2.setFont(font)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(460, 15, 86, 16))
        self.label_3.setFont(font)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(550, 15, 76, 16))
        self.label_4.setFont(font)
        self.pushButton_25 = QPushButton(self.centralwidget)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(20, 445, 51, 51))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        self.pushButton_25.setFont(font2)
        self.pushButton_25.setMouseTracking(False)
        self.pushButton_26 = QPushButton(self.centralwidget)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(130, 445, 51, 51))
        self.pushButton_26.setFont(font2)
        self.pushButton_26.setMouseTracking(False)
        self.pushButton_27 = QPushButton(self.centralwidget)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(75, 390, 51, 51))
        self.pushButton_27.setFont(font2)
        self.pushButton_27.setMouseTracking(False)
        self.pushButton_28 = QPushButton(self.centralwidget)
        self.pushButton_28.setObjectName(u"pushButton_28")
        self.pushButton_28.setGeometry(QRect(75, 500, 51, 51))
        self.pushButton_28.setFont(font2)
        self.pushButton_28.setMouseTracking(False)
        self.pushButton_29 = QPushButton(self.centralwidget)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(110, 330, 51, 51))
        self.pushButton_29.setFont(font2)
        self.pushButton_29.setMouseTracking(False)
        self.pushButton_30 = QPushButton(self.centralwidget)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.pushButton_30.setGeometry(QRect(40, 330, 51, 51))
        self.pushButton_30.setFont(font2)
        self.pushButton_30.setMouseTracking(False)
        self.doubleSpinBox = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(176, 215, 101, 26))
        self.doubleSpinBox.setWrapping(False)
        self.doubleSpinBox.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMinimum(-1.000000000000000)
        self.doubleSpinBox.setMaximum(180.000000000000000)
        self.doubleSpinBox.setSingleStep(10.000000000000000)
        self.doubleSpinBox.setValue(30.000000000000000)
        self.doubleSpinBox_2 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        self.doubleSpinBox_2.setGeometry(QRect(335, 215, 101, 26))
        self.doubleSpinBox_2.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_2.setDecimals(2)
        self.doubleSpinBox_2.setMinimum(0.010000000000000)
        self.doubleSpinBox_2.setMaximum(0.250000000000000)
        self.doubleSpinBox_2.setSingleStep(0.050000000000000)
        self.doubleSpinBox_2.setValue(0.150000000000000)
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(195, 35, 81, 26))
        self.lineEdit.setMaxLength(20)
        self.lineEdit.setAlignment(Qt.AlignCenter)
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(195, 65, 81, 26))
        self.lineEdit_2.setMaxLength(20)
        self.lineEdit_2.setAlignment(Qt.AlignCenter)
        self.lineEdit_3 = QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(195, 95, 81, 26))
        self.lineEdit_3.setMaxLength(20)
        self.lineEdit_3.setAlignment(Qt.AlignCenter)
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(195, 125, 81, 26))
        self.lineEdit_4.setMaxLength(20)
        self.lineEdit_4.setAlignment(Qt.AlignCenter)
        self.lineEdit_5 = QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(195, 155, 81, 26))
        self.lineEdit_5.setMaxLength(20)
        self.lineEdit_5.setAlignment(Qt.AlignCenter)
        self.lineEdit_6 = QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(195, 185, 81, 26))
        self.lineEdit_6.setMaxLength(20)
        self.lineEdit_6.setAlignment(Qt.AlignCenter)
        self.lineEdit_7 = QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(345, 185, 76, 26))
        self.lineEdit_7.setMaxLength(20)
        self.lineEdit_7.setAlignment(Qt.AlignCenter)
        self.lineEdit_8 = QLineEdit(self.centralwidget)
        self.lineEdit_8.setObjectName(u"lineEdit_8")
        self.lineEdit_8.setGeometry(QRect(345, 155, 76, 26))
        self.lineEdit_8.setMaxLength(20)
        self.lineEdit_8.setAlignment(Qt.AlignCenter)
        self.lineEdit_9 = QLineEdit(self.centralwidget)
        self.lineEdit_9.setObjectName(u"lineEdit_9")
        self.lineEdit_9.setGeometry(QRect(345, 125, 76, 26))
        self.lineEdit_9.setMaxLength(20)
        self.lineEdit_9.setAlignment(Qt.AlignCenter)
        self.lineEdit_10 = QLineEdit(self.centralwidget)
        self.lineEdit_10.setObjectName(u"lineEdit_10")
        self.lineEdit_10.setGeometry(QRect(345, 95, 76, 26))
        self.lineEdit_10.setMaxLength(20)
        self.lineEdit_10.setAlignment(Qt.AlignCenter)
        self.lineEdit_11 = QLineEdit(self.centralwidget)
        self.lineEdit_11.setObjectName(u"lineEdit_11")
        self.lineEdit_11.setGeometry(QRect(345, 65, 76, 26))
        self.lineEdit_11.setMaxLength(20)
        self.lineEdit_11.setAlignment(Qt.AlignCenter)
        self.lineEdit_12 = QLineEdit(self.centralwidget)
        self.lineEdit_12.setObjectName(u"lineEdit_12")
        self.lineEdit_12.setGeometry(QRect(345, 35, 76, 26))
        self.lineEdit_12.setMaxLength(20)
        self.lineEdit_12.setAlignment(Qt.AlignCenter)
        self.lineEdit_13 = QLineEdit(self.centralwidget)
        self.lineEdit_13.setObjectName(u"lineEdit_13")
        self.lineEdit_13.setGeometry(QRect(465, 35, 56, 26))
        self.lineEdit_13.setMaxLength(20)
        self.lineEdit_13.setAlignment(Qt.AlignCenter)
        self.lineEdit_13.setReadOnly(False)
        self.lineEdit_14 = QLineEdit(self.centralwidget)
        self.lineEdit_14.setObjectName(u"lineEdit_14")
        self.lineEdit_14.setGeometry(QRect(465, 65, 56, 26))
        self.lineEdit_14.setMaxLength(20)
        self.lineEdit_14.setAlignment(Qt.AlignCenter)
        self.lineEdit_14.setReadOnly(False)
        self.lineEdit_15 = QLineEdit(self.centralwidget)
        self.lineEdit_15.setObjectName(u"lineEdit_15")
        self.lineEdit_15.setGeometry(QRect(465, 95, 56, 26))
        self.lineEdit_15.setMaxLength(20)
        self.lineEdit_15.setAlignment(Qt.AlignCenter)
        self.lineEdit_15.setReadOnly(False)
        self.lineEdit_16 = QLineEdit(self.centralwidget)
        self.lineEdit_16.setObjectName(u"lineEdit_16")
        self.lineEdit_16.setGeometry(QRect(465, 125, 56, 26))
        self.lineEdit_16.setMaxLength(20)
        self.lineEdit_16.setAlignment(Qt.AlignCenter)
        self.lineEdit_16.setReadOnly(False)
        self.lineEdit_17 = QLineEdit(self.centralwidget)
        self.lineEdit_17.setObjectName(u"lineEdit_17")
        self.lineEdit_17.setGeometry(QRect(465, 155, 56, 26))
        self.lineEdit_17.setMaxLength(20)
        self.lineEdit_17.setAlignment(Qt.AlignCenter)
        self.lineEdit_17.setReadOnly(False)
        self.lineEdit_18 = QLineEdit(self.centralwidget)
        self.lineEdit_18.setObjectName(u"lineEdit_18")
        self.lineEdit_18.setGeometry(QRect(465, 185, 56, 26))
        self.lineEdit_18.setMaxLength(20)
        self.lineEdit_18.setAlignment(Qt.AlignCenter)
        self.lineEdit_18.setReadOnly(False)
        self.lineEdit_19 = QLineEdit(self.centralwidget)
        self.lineEdit_19.setObjectName(u"lineEdit_19")
        self.lineEdit_19.setGeometry(QRect(550, 35, 56, 26))
        self.lineEdit_19.setMaxLength(20)
        self.lineEdit_19.setAlignment(Qt.AlignCenter)
        self.lineEdit_20 = QLineEdit(self.centralwidget)
        self.lineEdit_20.setObjectName(u"lineEdit_20")
        self.lineEdit_20.setGeometry(QRect(550, 65, 56, 26))
        self.lineEdit_20.setMaxLength(20)
        self.lineEdit_20.setAlignment(Qt.AlignCenter)
        self.lineEdit_21 = QLineEdit(self.centralwidget)
        self.lineEdit_21.setObjectName(u"lineEdit_21")
        self.lineEdit_21.setGeometry(QRect(550, 95, 56, 26))
        self.lineEdit_21.setMaxLength(20)
        self.lineEdit_21.setAlignment(Qt.AlignCenter)
        self.lineEdit_22 = QLineEdit(self.centralwidget)
        self.lineEdit_22.setObjectName(u"lineEdit_22")
        self.lineEdit_22.setGeometry(QRect(550, 125, 56, 26))
        self.lineEdit_22.setMaxLength(20)
        self.lineEdit_22.setAlignment(Qt.AlignCenter)
        self.lineEdit_23 = QLineEdit(self.centralwidget)
        self.lineEdit_23.setObjectName(u"lineEdit_23")
        self.lineEdit_23.setGeometry(QRect(550, 155, 56, 26))
        self.lineEdit_23.setMaxLength(20)
        self.lineEdit_23.setAlignment(Qt.AlignCenter)
        self.lineEdit_24 = QLineEdit(self.centralwidget)
        self.lineEdit_24.setObjectName(u"lineEdit_24")
        self.lineEdit_24.setGeometry(QRect(550, 185, 56, 26))
        self.lineEdit_24.setMaxLength(20)
        self.lineEdit_24.setAlignment(Qt.AlignCenter)
        self.lineEdit_25 = QLineEdit(self.centralwidget)
        self.lineEdit_25.setObjectName(u"lineEdit_25")
        self.lineEdit_25.setGeometry(QRect(15, 250, 351, 31))
        self.lineEdit_25.setAlignment(Qt.AlignCenter)
        self.pushButton_31 = QPushButton(self.centralwidget)
        self.pushButton_31.setObjectName(u"pushButton_31")
        self.pushButton_31.setGeometry(QRect(435, 250, 61, 31))
        self.pushButton_31.setFont(font1)
        self.pushButton_32 = QPushButton(self.centralwidget)
        self.pushButton_32.setObjectName(u"pushButton_32")
        self.pushButton_32.setGeometry(QRect(505, 250, 66, 31))
        self.pushButton_32.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(45, 15, 86, 16))
        self.label_5.setFont(font)
        self.lineEdit_26 = QLineEdit(self.centralwidget)
        self.lineEdit_26.setObjectName(u"lineEdit_26")
        self.lineEdit_26.setGeometry(QRect(90, 95, 61, 26))
        self.lineEdit_26.setMaxLength(20)
        self.lineEdit_26.setAlignment(Qt.AlignCenter)
        self.lineEdit_27 = QLineEdit(self.centralwidget)
        self.lineEdit_27.setObjectName(u"lineEdit_27")
        self.lineEdit_27.setGeometry(QRect(90, 155, 61, 26))
        self.lineEdit_27.setMaxLength(20)
        self.lineEdit_27.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 95, 61, 26))
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 155, 71, 26))
        self.label_7.setAlignment(Qt.AlignCenter)
        self.lineEdit_28 = QLineEdit(self.centralwidget)
        self.lineEdit_28.setObjectName(u"lineEdit_28")
        self.lineEdit_28.setGeometry(QRect(90, 185, 61, 26))
        self.lineEdit_28.setMaxLength(20)
        self.lineEdit_28.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 185, 71, 26))
        self.label_8.setAlignment(Qt.AlignCenter)
        self.lineEdit_29 = QLineEdit(self.centralwidget)
        self.lineEdit_29.setObjectName(u"lineEdit_29")
        self.lineEdit_29.setGeometry(QRect(90, 125, 61, 26))
        self.lineEdit_29.setMaxLength(20)
        self.lineEdit_29.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 125, 61, 26))
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 215, 71, 26))
        self.label_10.setAlignment(Qt.AlignCenter)
        self.lineEdit_30 = QLineEdit(self.centralwidget)
        self.lineEdit_30.setObjectName(u"lineEdit_30")
        self.lineEdit_30.setGeometry(QRect(90, 215, 61, 26))
        self.lineEdit_30.setMaxLength(20)
        self.lineEdit_30.setAlignment(Qt.AlignCenter)
        self.pushButton_33 = QPushButton(self.centralwidget)
        self.pushButton_33.setObjectName(u"pushButton_33")
        self.pushButton_33.setGeometry(QRect(25, 35, 126, 26))
        font3 = QFont()
        font3.setBold(False)
        self.pushButton_33.setFont(font3)
        self.pushButton_34 = QPushButton(self.centralwidget)
        self.pushButton_34.setObjectName(u"pushButton_34")
        self.pushButton_34.setGeometry(QRect(25, 65, 126, 26))
        self.pushButton_34.setFont(font3)
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(195, 320, 221, 21))
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(25, 300, 146, 16))
        self.checkBox.setFont(font1)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(190, 295, 191, 26))
        self.label_11.setFont(font1)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(430, 295, 136, 26))
        self.label_12.setFont(font1)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.pushButton_38 = QPushButton(self.centralwidget)
        self.pushButton_38.setObjectName(u"pushButton_38")
        self.pushButton_38.setGeometry(QRect(430, 325, 51, 26))
        self.pushButton_38.setFont(font3)
        self.lineEdit_31 = QLineEdit(self.centralwidget)
        self.lineEdit_31.setObjectName(u"lineEdit_31")
        self.lineEdit_31.setGeometry(QRect(430, 505, 161, 26))
        self.lineEdit_31.setAlignment(Qt.AlignCenter)
        self.pushButton_39 = QPushButton(self.centralwidget)
        self.pushButton_39.setObjectName(u"pushButton_39")
        self.pushButton_39.setGeometry(QRect(485, 325, 51, 26))
        self.pushButton_39.setFont(font3)
        self.pushButton_40 = QPushButton(self.centralwidget)
        self.pushButton_40.setObjectName(u"pushButton_40")
        self.pushButton_40.setGeometry(QRect(540, 325, 51, 26))
        self.pushButton_40.setFont(font3)
        self.pushButton_41 = QPushButton(self.centralwidget)
        self.pushButton_41.setObjectName(u"pushButton_41")
        self.pushButton_41.setGeometry(QRect(540, 355, 51, 26))
        self.pushButton_41.setFont(font3)
        self.pushButton_42 = QPushButton(self.centralwidget)
        self.pushButton_42.setObjectName(u"pushButton_42")
        self.pushButton_42.setGeometry(QRect(430, 355, 51, 26))
        self.pushButton_42.setFont(font3)
        self.pushButton_43 = QPushButton(self.centralwidget)
        self.pushButton_43.setObjectName(u"pushButton_43")
        self.pushButton_43.setGeometry(QRect(485, 355, 51, 26))
        self.pushButton_43.setFont(font3)
        self.pushButton_44 = QPushButton(self.centralwidget)
        self.pushButton_44.setObjectName(u"pushButton_44")
        self.pushButton_44.setGeometry(QRect(540, 385, 51, 26))
        self.pushButton_44.setFont(font3)
        self.pushButton_45 = QPushButton(self.centralwidget)
        self.pushButton_45.setObjectName(u"pushButton_45")
        self.pushButton_45.setGeometry(QRect(430, 385, 51, 26))
        self.pushButton_45.setFont(font3)
        self.pushButton_46 = QPushButton(self.centralwidget)
        self.pushButton_46.setObjectName(u"pushButton_46")
        self.pushButton_46.setGeometry(QRect(485, 385, 51, 26))
        self.pushButton_46.setFont(font3)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(470, 480, 76, 26))
        self.label_13.setFont(font1)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.pushButton_47 = QPushButton(self.centralwidget)
        self.pushButton_47.setObjectName(u"pushButton_47")
        self.pushButton_47.setGeometry(QRect(530, 535, 61, 61))
        self.pushButton_47.setFont(font3)
        self.pushButton_48 = QPushButton(self.centralwidget)
        self.pushButton_48.setObjectName(u"pushButton_48")
        self.pushButton_48.setGeometry(QRect(430, 535, 41, 61))
        self.pushButton_48.setFont(font3)
        self.pushButton_49 = QPushButton(self.centralwidget)
        self.pushButton_49.setObjectName(u"pushButton_49")
        self.pushButton_49.setGeometry(QRect(475, 535, 51, 61))
        self.pushButton_49.setFont(font3)
        self.lineEdit_32 = QLineEdit(self.centralwidget)
        self.lineEdit_32.setObjectName(u"lineEdit_32")
        self.lineEdit_32.setGeometry(QRect(365, 250, 61, 31))
        self.lineEdit_32.setAlignment(Qt.AlignCenter)
        self.pushButton_50 = QPushButton(self.centralwidget)
        self.pushButton_50.setObjectName(u"pushButton_50")
        self.pushButton_50.setGeometry(QRect(540, 415, 51, 26))
        self.pushButton_50.setFont(font3)
        self.pushButton_51 = QPushButton(self.centralwidget)
        self.pushButton_51.setObjectName(u"pushButton_51")
        self.pushButton_51.setGeometry(QRect(485, 415, 51, 26))
        self.pushButton_51.setFont(font3)
        self.pushButton_52 = QPushButton(self.centralwidget)
        self.pushButton_52.setObjectName(u"pushButton_52")
        self.pushButton_52.setGeometry(QRect(430, 415, 51, 26))
        self.pushButton_52.setFont(font3)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(420, 730, 191, 26))
        font4 = QFont()
        font4.setPointSize(13)
        font4.setBold(True)
        self.label_14.setFont(font4)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(140, 425, 61, 26))
        self.label_15.setFont(font1)
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(105, 380, 61, 26))
        self.label_16.setFont(font1)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(-10, 495, 61, 21))
        self.label_17.setFont(font1)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(35, 535, 56, 26))
        self.label_18.setFont(font1)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(140, 320, 61, 26))
        self.label_19.setFont(font1)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 320, 61, 26))
        self.label_20.setFont(font1)
        self.label_20.setAlignment(Qt.AlignCenter)
        self.pushButton_54 = QPushButton(self.centralwidget)
        self.pushButton_54.setObjectName(u"pushButton_54")
        self.pushButton_54.setGeometry(QRect(550, 220, 56, 21))
        self.pushButton_54.setFont(font3)
        self.pushButton_53 = QPushButton(self.centralwidget)
        self.pushButton_53.setObjectName(u"pushButton_53")
        self.pushButton_53.setGeometry(QRect(100, 580, 151, 31))
        self.pushButton_53.setFont(font3)
        self.pushButton_55 = QPushButton(self.centralwidget)
        self.pushButton_55.setObjectName(u"pushButton_55")
        self.pushButton_55.setGeometry(QRect(100, 620, 151, 31))
        self.pushButton_55.setFont(font3)
        self.pushButton_56 = QPushButton(self.centralwidget)
        self.pushButton_56.setObjectName(u"pushButton_56")
        self.pushButton_56.setGeometry(QRect(100, 660, 71, 31))
        self.pushButton_56.setFont(font3)
        self.pushButton_57 = QPushButton(self.centralwidget)
        self.pushButton_57.setObjectName(u"pushButton_57")
        self.pushButton_57.setGeometry(QRect(180, 660, 71, 31))
        self.pushButton_57.setFont(font3)
        self.pushButton_58 = QPushButton(self.centralwidget)
        self.pushButton_58.setObjectName(u"pushButton_58")
        self.pushButton_58.setGeometry(QRect(100, 700, 71, 31))
        self.pushButton_58.setFont(font3)
        self.pushButton_59 = QPushButton(self.centralwidget)
        self.pushButton_59.setObjectName(u"pushButton_59")
        self.pushButton_59.setGeometry(QRect(180, 700, 71, 31))
        self.pushButton_59.setFont(font3)
        self.horizontalScrollBar = QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setObjectName(u"horizontalScrollBar")
        self.horizontalScrollBar.setGeometry(QRect(260, 581, 160, 31))
        self.horizontalScrollBar.setCursor(QCursor(Qt.SizeHorCursor))
        self.horizontalScrollBar.setMaximum(100)
        self.horizontalScrollBar.setSingleStep(5)
        self.horizontalScrollBar.setValue(50)
        self.horizontalScrollBar.setOrientation(Qt.Horizontal)
        self.horizontalScrollBar.setInvertedAppearance(False)
        self.pushButton_60 = QPushButton(self.centralwidget)
        self.pushButton_60.setObjectName(u"pushButton_60")
        self.pushButton_60.setGeometry(QRect(260, 620, 81, 31))
        self.pushButton_60.setFont(font3)
        self.doubleSpinBox_3 = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_3.setObjectName(u"doubleSpinBox_3")
        self.doubleSpinBox_3.setGeometry(QRect(350, 620, 71, 31))
        self.doubleSpinBox_3.setAlignment(Qt.AlignCenter)
        self.doubleSpinBox_3.setDecimals(0)
        self.doubleSpinBox_3.setMinimum(0.000000000000000)
        self.doubleSpinBox_3.setMaximum(100.000000000000000)
        self.doubleSpinBox_3.setSingleStep(5.000000000000000)
        self.doubleSpinBox_3.setValue(50.000000000000000)
        self.lineEdit_33 = QLineEdit(self.centralwidget)
        self.lineEdit_33.setObjectName(u"lineEdit_33")
        self.lineEdit_33.setGeometry(QRect(340, 660, 61, 21))
        self.lineEdit_33.setMaxLength(20)
        self.lineEdit_33.setAlignment(Qt.AlignCenter)
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(270, 660, 61, 21))
        self.label_21.setAlignment(Qt.AlignCenter)
        self.lineEdit_34 = QLineEdit(self.centralwidget)
        self.lineEdit_34.setObjectName(u"lineEdit_34")
        self.lineEdit_34.setGeometry(QRect(340, 690, 61, 21))
        self.lineEdit_34.setMaxLength(20)
        self.lineEdit_34.setAlignment(Qt.AlignCenter)
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(270, 690, 61, 21))
        self.label_22.setAlignment(Qt.AlignCenter)
        self.pushButton_61 = QPushButton(self.centralwidget)
        self.pushButton_61.setObjectName(u"pushButton_61")
        self.pushButton_61.setGeometry(QRect(430, 445, 51, 26))
        self.pushButton_61.setFont(font3)
        self.pushButton_62 = QPushButton(self.centralwidget)
        self.pushButton_62.setObjectName(u"pushButton_62")
        self.pushButton_62.setGeometry(QRect(485, 445, 51, 26))
        self.pushButton_62.setFont(font3)
        self.pushButton_63 = QPushButton(self.centralwidget)
        self.pushButton_63.setObjectName(u"pushButton_63")
        self.pushButton_63.setGeometry(QRect(540, 445, 51, 26))
        self.pushButton_63.setFont(font3)
        self.pushButton_64 = QPushButton(self.centralwidget)
        self.pushButton_64.setObjectName(u"pushButton_64")
        self.pushButton_64.setGeometry(QRect(10, 650, 81, 25))
        self.spinBox = QSpinBox(self.centralwidget)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(10, 620, 81, 26))
        self.spinBox.setLayoutDirection(Qt.LeftToRight)
        self.spinBox.setAlignment(Qt.AlignCenter)
        self.spinBox.setMinimum(-1000)
        self.spinBox.setMaximum(1000)
        self.spinBox.setValue(10)
        self.textEdit_2 = QTextEdit(self.centralwidget)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(30, 579, 31, 31))
        self.spinBox_2 = QSpinBox(self.centralwidget)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(430, 610, 81, 26))
        self.spinBox_2.setLayoutDirection(Qt.LeftToRight)
        self.spinBox_2.setAlignment(Qt.AlignCenter)
        self.spinBox_2.setMinimum(-1000)
        self.spinBox_2.setMaximum(1000)
        self.spinBox_2.setValue(0)
        self.spinBox_3 = QSpinBox(self.centralwidget)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(430, 640, 81, 26))
        self.spinBox_3.setLayoutDirection(Qt.LeftToRight)
        self.spinBox_3.setAlignment(Qt.AlignCenter)
        self.spinBox_3.setMinimum(-1000)
        self.spinBox_3.setMaximum(1000)
        self.spinBox_3.setValue(0)
        self.spinBox_4 = QSpinBox(self.centralwidget)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(430, 670, 81, 26))
        self.spinBox_4.setLayoutDirection(Qt.LeftToRight)
        self.spinBox_4.setAlignment(Qt.AlignCenter)
        self.spinBox_4.setMinimum(-1000)
        self.spinBox_4.setMaximum(1000)
        self.spinBox_4.setValue(0)
        self.pushButton_65 = QPushButton(self.centralwidget)
        self.pushButton_65.setObjectName(u"pushButton_65")
        self.pushButton_65.setGeometry(QRect(430, 700, 81, 21))
        self.pushButton_65.setFont(font3)
        self.pushButton_66 = QPushButton(self.centralwidget)
        self.pushButton_66.setObjectName(u"pushButton_66")
        self.pushButton_66.setGeometry(QRect(600, 250, 66, 31))
        self.pushButton_66.setFont(font1)
        self.pushButton_67 = QPushButton(self.centralwidget)
        self.pushButton_67.setObjectName(u"pushButton_67")
        self.pushButton_67.setGeometry(QRect(275, 350, 51, 26))
        self.pushButton_67.setFont(font3)
        self.pushButton_68 = QPushButton(self.centralwidget)
        self.pushButton_68.setObjectName(u"pushButton_68")
        self.pushButton_68.setGeometry(QRect(275, 380, 51, 26))
        self.pushButton_68.setFont(font3)
        self.pushButton_69 = QPushButton(self.centralwidget)
        self.pushButton_69.setObjectName(u"pushButton_69")
        self.pushButton_69.setGeometry(QRect(275, 410, 51, 26))
        self.pushButton_69.setFont(font3)
        self.pushButton_70 = QPushButton(self.centralwidget)
        self.pushButton_70.setObjectName(u"pushButton_70")
        self.pushButton_70.setGeometry(QRect(330, 380, 51, 26))
        self.pushButton_70.setFont(font3)
        self.pushButton_71 = QPushButton(self.centralwidget)
        self.pushButton_71.setObjectName(u"pushButton_71")
        self.pushButton_71.setGeometry(QRect(220, 380, 51, 26))
        self.pushButton_71.setFont(font3)
        self.pushButton_72 = QPushButton(self.centralwidget)
        self.pushButton_72.setObjectName(u"pushButton_72")
        self.pushButton_72.setGeometry(QRect(330, 350, 51, 26))
        self.pushButton_72.setFont(font3)
        self.pushButton_73 = QPushButton(self.centralwidget)
        self.pushButton_73.setObjectName(u"pushButton_73")
        self.pushButton_73.setGeometry(QRect(220, 440, 51, 26))
        self.pushButton_73.setFont(font3)
        self.pushButton_74 = QPushButton(self.centralwidget)
        self.pushButton_74.setObjectName(u"pushButton_74")
        self.pushButton_74.setGeometry(QRect(220, 410, 51, 26))
        self.pushButton_74.setFont(font3)
        self.pushButton_75 = QPushButton(self.centralwidget)
        self.pushButton_75.setObjectName(u"pushButton_75")
        self.pushButton_75.setGeometry(QRect(275, 440, 51, 26))
        self.pushButton_75.setFont(font3)
        self.pushButton_76 = QPushButton(self.centralwidget)
        self.pushButton_76.setObjectName(u"pushButton_76")
        self.pushButton_76.setGeometry(QRect(330, 440, 51, 26))
        self.pushButton_76.setFont(font3)
        self.pushButton_77 = QPushButton(self.centralwidget)
        self.pushButton_77.setObjectName(u"pushButton_77")
        self.pushButton_77.setGeometry(QRect(330, 410, 51, 26))
        self.pushButton_77.setFont(font3)
        self.pushButton_78 = QPushButton(self.centralwidget)
        self.pushButton_78.setObjectName(u"pushButton_78")
        self.pushButton_78.setGeometry(QRect(220, 350, 51, 26))
        self.pushButton_78.setFont(font3)
        self.pushButton_79 = QPushButton(self.centralwidget)
        self.pushButton_79.setObjectName(u"pushButton_79")
        self.pushButton_79.setGeometry(QRect(275, 470, 51, 26))
        self.pushButton_79.setFont(font3)
        self.pushButton_80 = QPushButton(self.centralwidget)
        self.pushButton_80.setObjectName(u"pushButton_80")
        self.pushButton_80.setGeometry(QRect(330, 470, 51, 26))
        self.pushButton_80.setFont(font3)
        self.pushButton_81 = QPushButton(self.centralwidget)
        self.pushButton_81.setObjectName(u"pushButton_81")
        self.pushButton_81.setGeometry(QRect(220, 470, 51, 26))
        self.pushButton_81.setFont(font3)
        self.checkBox_2 = QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(170, 15, 16, 16))
        self.checkBox_2.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 692, 19))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"UR Task Planner", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Actual Q(deg)", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u">", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Actual TCP(m)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"TCP Speed", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Tool Force", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"\u2190", None))
        self.pushButton_26.setText(QCoreApplication.translate("MainWindow", u"\u2192", None))
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"\u2191", None))
        self.pushButton_28.setText(QCoreApplication.translate("MainWindow", u"\u2193", None))
        self.pushButton_29.setText(QCoreApplication.translate("MainWindow", u"\u219f", None))
        self.pushButton_30.setText(QCoreApplication.translate("MainWindow", u"\u21a1", None))
#if QT_CONFIG(accessibility)
        self.doubleSpinBox.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.doubleSpinBox.setSpecialValueText("")
        self.doubleSpinBox.setSuffix(QCoreApplication.translate("MainWindow", u" deg/s", None))
        self.doubleSpinBox_2.setSuffix(QCoreApplication.translate("MainWindow", u" m/s", None))
        self.lineEdit.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_2.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_3.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_4.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_5.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_6.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_7.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_8.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_9.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_10.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_11.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_12.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_13.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_14.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_15.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_16.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_17.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_18.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_19.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_20.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_21.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_22.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_23.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_24.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineEdit_25.setText(QCoreApplication.translate("MainWindow", u"[ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]", None))
        self.pushButton_31.setText(QCoreApplication.translate("MainWindow", u"Get Q", None))
        self.pushButton_32.setText(QCoreApplication.translate("MainWindow", u"Get TCP", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Robot Status", None))
        self.lineEdit_26.setText(QCoreApplication.translate("MainWindow", u"False", None))
        self.lineEdit_27.setText(QCoreApplication.translate("MainWindow", u"No Ctrl", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"EMO", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Robot Mode", None))
        self.lineEdit_28.setText(QCoreApplication.translate("MainWindow", u"Power off", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Robot Status", None))
        self.lineEdit_29.setText(QCoreApplication.translate("MainWindow", u"False", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Protective", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Safety Mode", None))
        self.lineEdit_30.setText(QCoreApplication.translate("MainWindow", u"Normal", None))
        self.pushButton_33.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.pushButton_34.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.textEdit.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Gulim';\">{-350.0, 97.0, 120.0, 0.0, 0.0, 0.0}</span></p></body></html>", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Tool Directions", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"* Start Extra Task Planner", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"* Basic Task Planner", None))
        self.pushButton_38.setText(QCoreApplication.translate("MainWindow", u"Tool 1 A", None))
        self.lineEdit_31.setText(QCoreApplication.translate("MainWindow", u"Default Task", None))
        self.pushButton_39.setText(QCoreApplication.translate("MainWindow", u"Tool 1 D", None))
        self.pushButton_40.setText(QCoreApplication.translate("MainWindow", u"Task 3", None))
        self.pushButton_41.setText(QCoreApplication.translate("MainWindow", u"Task 6", None))
        self.pushButton_42.setText(QCoreApplication.translate("MainWindow", u"Tool 2 D", None))
        self.pushButton_43.setText(QCoreApplication.translate("MainWindow", u"Tool 2 D", None))
        self.pushButton_44.setText(QCoreApplication.translate("MainWindow", u"Task 9", None))
        self.pushButton_45.setText(QCoreApplication.translate("MainWindow", u"Tip 1 A", None))
        self.pushButton_46.setText(QCoreApplication.translate("MainWindow", u"TIp 1 D", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Task Name", None))
        self.pushButton_47.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.pushButton_48.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.pushButton_49.setText(QCoreApplication.translate("MainWindow", u"Pause", None))
        self.lineEdit_32.setText(QCoreApplication.translate("MainWindow", u"degree", None))
        self.pushButton_50.setText(QCoreApplication.translate("MainWindow", u"Task 12", None))
        self.pushButton_51.setText(QCoreApplication.translate("MainWindow", u"Tip 2 D", None))
        self.pushButton_52.setText(QCoreApplication.translate("MainWindow", u"Tip 2 A", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Powered by KORAS", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"+Y", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"-X", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"-Y", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"+X", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"+Z", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"-Z", None))
        self.pushButton_54.setText(QCoreApplication.translate("MainWindow", u"Set Zero", None))
        self.pushButton_53.setText(QCoreApplication.translate("MainWindow", u"Gripper Initialize", None))
        self.pushButton_55.setText(QCoreApplication.translate("MainWindow", u"Gripper Stop", None))
        self.pushButton_56.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.pushButton_57.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.pushButton_58.setText(QCoreApplication.translate("MainWindow", u"Vac On", None))
        self.pushButton_59.setText(QCoreApplication.translate("MainWindow", u"Vac Off", None))
        self.pushButton_60.setText(QCoreApplication.translate("MainWindow", u"Finger Move", None))
        self.doubleSpinBox_3.setSuffix(QCoreApplication.translate("MainWindow", u" %", None))
        self.lineEdit_33.setText(QCoreApplication.translate("MainWindow", u"0.0 %", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Finger pos", None))
        self.lineEdit_34.setText(QCoreApplication.translate("MainWindow", u"0 mA", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Current", None))
        self.pushButton_61.setText(QCoreApplication.translate("MainWindow", u"Init", None))
        self.pushButton_62.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.pushButton_63.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.pushButton_64.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.spinBox.setSuffix(QCoreApplication.translate("MainWindow", u" mm", None))
        self.textEdit_2.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:'Ubuntu'; font-size:11pt;\">z</span></p></body></html>", None))
        self.spinBox_2.setSuffix(QCoreApplication.translate("MainWindow", u" mm", None))
        self.spinBox_2.setPrefix(QCoreApplication.translate("MainWindow", u"X: ", None))
        self.spinBox_3.setSuffix(QCoreApplication.translate("MainWindow", u" mm", None))
        self.spinBox_3.setPrefix(QCoreApplication.translate("MainWindow", u"Y: ", None))
        self.spinBox_4.setSuffix(QCoreApplication.translate("MainWindow", u" mm", None))
        self.spinBox_4.setPrefix(QCoreApplication.translate("MainWindow", u"Z: ", None))
        self.pushButton_65.setText(QCoreApplication.translate("MainWindow", u"Set TCP", None))
        self.pushButton_66.setText(QCoreApplication.translate("MainWindow", u"MOVE", None))
        self.pushButton_67.setText(QCoreApplication.translate("MainWindow", u"Task 17", None))
        self.pushButton_68.setText(QCoreApplication.translate("MainWindow", u"Task 20", None))
        self.pushButton_69.setText(QCoreApplication.translate("MainWindow", u"Task 23", None))
        self.pushButton_70.setText(QCoreApplication.translate("MainWindow", u"Task 21", None))
        self.pushButton_71.setText(QCoreApplication.translate("MainWindow", u"Task 19", None))
        self.pushButton_72.setText(QCoreApplication.translate("MainWindow", u"Task 18", None))
        self.pushButton_73.setText(QCoreApplication.translate("MainWindow", u"Task 25", None))
        self.pushButton_74.setText(QCoreApplication.translate("MainWindow", u"Task 22", None))
        self.pushButton_75.setText(QCoreApplication.translate("MainWindow", u"Task 26", None))
        self.pushButton_76.setText(QCoreApplication.translate("MainWindow", u"Task 27", None))
        self.pushButton_77.setText(QCoreApplication.translate("MainWindow", u"Task 24", None))
        self.pushButton_78.setText(QCoreApplication.translate("MainWindow", u"Task 16", None))
        self.pushButton_79.setText(QCoreApplication.translate("MainWindow", u"Task 29", None))
        self.pushButton_80.setText(QCoreApplication.translate("MainWindow", u"Task 30", None))
        self.pushButton_81.setText(QCoreApplication.translate("MainWindow", u"Task 28", None))
        self.checkBox_2.setText("")
    # retranslateUi

